export const TYPES={

    Application:Symbol.for('Application'),
    UserController:Symbol.for('UserController'),
    LoggerService:Symbol.for('loggerService'),
    AuthController:Symbol.for('AuthController'),
    ExeptionFilter:Symbol.for('ExeptionFilter'),
    PrismaService: Symbol.for('PrismaService'),
    UserService: Symbol.for('UserService'),
    UserRepository:Symbol.for('UserRepository'),
    ConfigService:Symbol.for('ConfigService'),    
    AuthMiddleware:Symbol.for('AuthMiddleware'),    
    AuthService:Symbol.for('AuthService'),    
    PassageRepository:Symbol.for('PassageRepository'),    
    PassageService:Symbol.for('PassageService'),    
    PassageController:Symbol.for('PassageController'),    
    TiketRepository:Symbol.for('TiketRepository'),    
    TiketService:Symbol.for('TiketService'),    
    TiketController:Symbol.for('TiketController'),    
    TiketCategoryRepository:Symbol.for('TiketCategoryRepository'),    
    TiketCategoryService:Symbol.for('TiketCategoryService'),    
    TiketCategoryController:Symbol.for('TiketCategoryController'),    
    PlaceRepository:Symbol.for('PlaceRepository'),    
    PlaceService:Symbol.for('PlaceService'),    
    PlaceController:Symbol.for('PlaceController'),    
    PlaneRepository:Symbol.for('PlaneRepository'),    
    PlaneService:Symbol.for('PlaneService'),    
    PlaneController:Symbol.for('PlaneController'),    
};

